apiVersion: apps/v1
kind: Deployment
metadata:
  name: msDocument
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msDocument
  template:
    metadata:
      labels:
        app: msDocument
    spec:
      containers:
      - name: msDocument
        image: ghofrane694/msDocument
        ports:
        - containerPort: 5004
